apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dzanto-cluster
  region: eu-north-1

nodeGroups:
  - name: ng-1
    instanceType: t3.micro
    desiredCapacity: 2 # количество инстансов
  - name: ng-2
    instanceType: t3.micro
    desiredCapacity: 2
    
