apiVersion: v1
kind: Pod
metadata:
  name: my-web
  labels:
    any_labels_key: any_labels_value
    second_label: second_value
spec:
  containers:
  - name: container-apache
    image: httpd:latest
    ports:
      - containerPort: 80
  - name: container-tomcat
    image: tomcat: 8.5.38
    ports:
      - containerPort: 8080
